### ISSUE TITLE
As an applicant, I want confirmation my application was successfully submitted and a description of what will happen from here.

### ISSUE THREAD

**Issue by dubharmonic** [flexion/fs-intake-module#140]
Definition of Done
- [ ] Acceptance criteria met (UAT)
- [ ] Code refactored for clarity
- [ ] Framework code decoupled from ours
- [ ] Source code committed
- [ ] Unit test coverage of our code = 100%
- [ ] Code reviewed (or developed by pair)
- [ ] Security reviewed and reported
- [ ] No local design debt
- [ ] Visual design review passed
- [ ] Build process updated
- [ ] Source documentation generated
- [ ] API documentation generated
- [ ] Code quality checks passed
- [ ] Guides and training draft updated
- [ ] Security & privacy gates passed

**Comment by lauraGgit** [comment]
Looks like this one is probably 2 stories? one for NC and one for temp?

Am I correct that the NC confirmation is done @dubharmonic?

**Comment by dubharmonic** [comment]
Split into 2 stories, one for noncommercial and one for temp outfitter
