### ISSUE TITLE
As an applicant, I would like a way to cancel my application after I submit it.

### ISSUE THREAD

**Issue by dubharmonic** [flexion/fs-intake-module#142]
Acceptance Criteria
- [x] Can they cancel after being accepted? No.
- [x] Cancel button on the view application screen for an authenticated user.
- [x] Confirmation screen and confirmation email provide a link back to the application screen showing that an application can be cancelled before being accepted.

Definition of Done
- [x] Code unit / e2e tested and comply with QWASP
- [x] No new security vulnerabilities 
- [x] Flexion code review
- [x] Documentation / readme.md updated
- [x] Docker updated
- [x] Compare finished design with mockup
- [x] Usability tested

Tasks
- [x] create branch (seth)
- [x] create and review a mockup for list with Nate
- [x] create and review a mockup for view with Nate
- [x] create cancel button component ( Seth )
- [x] add a cancel button to both the list and single application views (seth)
- [x] Are you sure? prompt (browser's built in version)
- [x] add an update API endpoint for both permit types
- [x] make it clear that only the authenticated user can view or cancel their applications (seth & peter)

**Comment by dubharmonic** [comment]
Requires some way for the applicant to authenticate and view a list of applications.

**Comment by npage123** [comment]
Preliminary mockup - ![applicant-list-page-rd1-01](https://user-images.githubusercontent.com/12956624/30703098-5be4cf04-9eb4-11e7-9d84-582380113306.jpg)
