### ISSUE TITLE
As an applicant, I would like to be able to check back on the application after I submit it.

### ISSUE THREAD

**Issue by dubharmonic** [flexion/fs-intake-module#143]
Acceptance Criteria
- [x] Includes the ability to see past applications and see a status.
- [x] Add a "View applications" link next to the logout link in the header.
- [x] Doesn't include editing

Definition of Done
- [x] Code unit / e2e tested and comply with QWASP
- [x] No new security vulnerabilities 
- [x] Flexion code review
- [x] Documentation / readme.md updated
- [x] Docker updated
- [x] Compare finished design with mockup
- [x] Usability tested

Tasks
- [x] Add applications link to header
- [x] Add screen for my applications list (similar to the admin screen) (seth & chris)
- [x] Add screen for viewing one of my applications (similar to the admin screen) (seth & chris)
- [x] Review columns and fields, make adjustments (status columns for example)
- [x] Add CTAs to apply for permits
- [x] Include on hold message on application detail if exists, SA contact info
- [x] add a column to permit applications for owner's email from login.gov (Eric)
- [x] save authenticated email to new column in application tables (Eric)
- [x] add API endpoint for viewing my permit applications (Eric)

**Comment by dubharmonic** [comment]
We'll need to talk about authentication before completing this story.

**Comment by npage123** [comment]
Preliminary mockup
![applicant-list-page-rd1-01](https://user-images.githubusercontent.com/12956624/30705848-3c5b6bae-9ebc-11e7-8f13-e6e7185b0cdf.jpg)

**Comment by colinpmacarthur** [comment]
I took a look at this and identified a few issues:

[  ] **1. I appear to be able to see everyone else's applications.** When I login, and click "View applications," I see a list of many applications I didn't submit.

[  ] **2. Should this list have the same red, bold text on dates that the admin's list does?** I'm worried this won't make sense to the admin.

[  ] **3. The "View Applicants" link should be in sentence case. "View applications."**

[  ] **4. The table and the "apply for another permit" button are misaligned.**
<img width="1016" alt="screen shot 2017-09-22 at 7 12 01 pm" src="https://user-images.githubusercontent.com/2092076/30767457-9cfdb246-9fca-11e7-8e9e-fc1a87a59158.png">

[  ] **5. Should there be more space between the end of the details page and the footer?**
Currently, details block rams straight into the top of the footer.

<img width="487" alt="screen shot 2017-09-22 at 7 12 34 pm" src="https://user-images.githubusercontent.com/2092076/30767469-b7192d54-9fca-11e7-8c4e-90fcb9f4f29f.png">
