### ISSUE TITLE
As an applicant whose activity requires a permit, I would like to know whether or not the temp outfitter activity I am requesting requires a permit fee and how much that fee will likely be for my proposed activity.

### ISSUE THREAD

**Issue by dubharmonic** [flexion/fs-intake-module#146]
Definition of Done
- [x] Code unit / e2e tested and comply with QWASP
- [x] No new security vulnerabilities 
- [x] Flexion code review
- [x] Documentation / readme.md updated
- [x] Docker updated
- [x] Visual design review
- [x] Usability tested

**Comment by npage123** [comment]
@colinpmacarthur - Here's the flat rate fee table that I found however, do you know where I could look to see if there are additional fees based on the specific activity?

**Comment by dubharmonic** [comment]
Feedback:
* Order of information?
* Table header color accessibility?
