### ISSUE TITLE
As a non-commercial group use applicant, I want to understand the process for submitting an application (what steps I will take now, what will happen after that, etc.). In particular, I want to know what documents I will be required to compile and attach.

### ISSUE THREAD

**Issue by dubharmonic** [flexion/fs-intake-module#149]
Definition of Done
- [x] Code unit / e2e tested and comply with QWASP
- [x] No new security vulnerabilities 
- [x] Flexion code review
- [x] Documentation / readme.md updated
- [x] Docker updated
- [x] Visual design review
- [x] Usability tested

Tasks
- [x] Pair with Colin for planning
- [x] Pair with developer for making changes to the code

**Comment by dubharmonic** [comment]
Before an applicant gets started they should be able to learn about the application lifecycle.

**Comment by dubharmonic** [comment]
something like a FAQ - here’s how the process works, general what to expect, take insights from the form and expose them in a screen available before authenticating, maybe a paragraph?

**Comment by npage123** [comment]
Please add the following content list to the non-commercial form below the forest name at top. See screenshot for reference.

Application process

1. Fill out and submit the application.
2. Your application will be reviewed by our staff within 48 hours.
3. If additional information is needed, a representative of the National Forest Service will contact you via email to resolve any issues.
4. After the application has been reviewed, you will be notified of the application status. If accepted, it will then move on to a special use administrator for approval. 
5. If your application is approved, you will receive your permit via U.S. mail within 2 weeks of approval.

<img width="869" alt="screen shot 2017-09-01 at 3 29 25 pm" src="https://user-images.githubusercontent.com/12956624/29986730-5ff4eb54-8f2a-11e7-9758-0f0b3d0d715e.png">

**Comment by dubharmonic** [comment]
Ready for frontend development.

**Comment by dubharmonic** [comment]
@npage123 discuss with @colinpmacarthur before moving forward

**Comment by npage123** [comment]
@sethalt @thegoldentoilet - Ready for development. See last comment from Nate for details.
