### ISSUE TITLE
Optimize the current prototype 

### ISSUE THREAD

**Issue by sethalt** [flexion/fs-intake-module#15]

**Comment by pvd-flexion** [comment]
Here are some improvements Eric, Nate and I are working on reviewing and testing.
Form field labels. options:
 - Add in the "optional" label
 - Indicate at top of form that all fields are required and only label options fields

Call out form field validation errors when taking focus off a field that has not met the requirements.

Permit Holder address should only be visible is user indicates it’s different than the Organization address. Let’s switch the indicator to a check box.

Let’s make sure we have the ability to add description under all field labels, similar to estimated number of participants. We may want to be able to add those to Description and Location and have the ability to easily add to other as needed or testing suggests.

Pre-filling the date field with today’s date doesn’t seem useful, considering these will most likely be filled out ahead of the current date. Let’s switch date format to follow standards and add time as a separate line

Design Items:

Clearer visual separation of sections. (design challenge)

All permit holders should appear to be under the same section (Permit Holders). Currently when you add a second permit holder it appears to be in a new section. I’m assuming from their prototype there can only be two permit holders. In that case we should change the “add another permit holder” to “ Add a second permit holder” and remove it after adding and adding a remove UI element ( like a delete X) next to the second permit holders title. Not sure red is the best color for the “add new permit holder” button. (design challenge)
