### ISSUE TITLE
As an applicant, I receive the name, email address and phone number of the Forest Service special uses administrator receiving my application.

### ISSUE THREAD

**Issue by dubharmonic** [flexion/fs-intake-module#155]
Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities 
- [ ] Flexion code review
- [ ] Documentation / readme.md updated
- [ ] Docker updated
- [ ] Visual design review
- [ ] Usability tested

**Comment by dubharmonic** [comment]
(both noncommercial and temp outfitter)

**Comment by sethalt** [comment]
@dubharmonic have we started on this?
