### ISSUE TITLE
As a Forest Service special uses administrator, I would like to receive an email when a new application is submitted to my Forest.

### ISSUE THREAD

**Issue by dubharmonic** [flexion/fs-intake-module#157]
Definition of Done
- [x] Code unit / e2e tested and comply with QWASP
- [x] No new security vulnerabilities 
- [x] Flexion code review
- [x] Documentation / readme.md updated
- [x] Docker updated
- [x] Visual design review
- [ ] Usability tested

Tasks
- [x] Design / UX: Copy
- [x] Design / UX: 18F approves copy
- [x] Server: choose a location to store the email addresses for admins for each forest
- [x] Server: add local storage handler to send the admin to the correct location after they have logged in
- [x] Server: Add link in the email to go directly to the application
- [x] Server: Create email template
- [x] Server: Trigger email when a new application is submitted

**Comment by dubharmonic** [comment]
What does this email look like?
How do we let the admin know that an email was send to the applicant?

**Comment by sethalt** [comment]
@lauraGgit we probably need a VCAP for the email address of the special use admin(s) that should receive the notification of the new application.

**Comment by npage123** [comment]
Proposed text for temp outfitter version:

Subject Line: A new permit has been submitted to the Mt. Baker-Snoqualmie National Forest.


Application details
*********************************

Permit type:
Business name:
Start date:
End date:
Number of trips:
Number of participants:
Services:

Go to https://fs-intake-staging.app.cloud.gov/admin/applications to log in.



Proposed text for noncommercial version:

Subject Line: A new permit has been submitted to the Mt. Baker-Snoqualmie National Forest.


Application details
*********************

Permit type:
Event name:
Start date:
End date:
Number of participants:
Number of spectators:
Location:

Go to https://fs-intake-staging.app.cloud.gov/admin/applications to log in.
