### ISSUE TITLE
As a Forest Service special uses administrator, I would like to receive an email if an application has been cancelled by the application submitter.

### ISSUE THREAD

**Issue by dubharmonic** [flexion/fs-intake-module#158]
Acceptance Criteria
- [x] Include all of the information in the initial email about the application

Definition of Done
- [x] Code unit / e2e tested and comply with QWASP
- [x] No new security vulnerabilities 
- [x] Flexion code review
- [x] Documentation / readme.md updated
- [x] Docker updated
- [x] Compare finished design with mockup
- [ ] Usability tested

Tasks
- [x] Design / UX: Copy (Peter)
- [x] Design / UX: 18F approves copy
- [x] Design review of screenshot / content (Peter & Eric
- [x] Server: Create email template (Eric)
- [x] Server: Trigger email when application status is set to 'cancelled' (Eric)

**Comment by npage123** [comment]
Preliminary temp-outfitter cancel email content screenshot:
<img width="555" alt="screen shot 2017-09-21 at 4 19 21 pm" src="https://user-images.githubusercontent.com/12956624/30719365-d9ff6870-9ee8-11e7-8801-9c779be8b324.png">

Preliminary noncommercial cancel email content screenshot:
<img width="555" alt="screen shot 2017-09-21 at 4 19 10 pm" src="https://user-images.githubusercontent.com/12956624/30719369-e2f47cc2-9ee8-11e7-8720-49cbbb214fc2.png">

**Comment by npage123** [comment]
Temp outfitter version text (should end up looking like above screenshot):

Subject Line: The following permit application to the Mt. Baker-Snoqualmie National Forest has been cancelled.


Application details
*********************************

Permit type:
Business name:
Start date:
End date:
Number of trips:
Number of participants:
Services:

Go to https://fs-intake-staging.app.cloud.gov/admin/applications to log in.

Noncommercial version text (should end up looking like above screenshot):

Subject Line: The following permit application to the Mt. Baker-Snoqualmie National Forest has been cancelled.


Application details
*********************

Permit type:
Event name:
Start date:
End date:
Number of participants:
Number of spectators:
Location:

Go to https://fs-intake-staging.app.cloud.gov/admin/applications to log in.
