### ISSUE TITLE
As an applicant, I would like to receive an email with the reason that my application has not been accepted.

### ISSUE THREAD

**Issue by dubharmonic** [flexion/fs-intake-module#159]
Definition of Done
- [x] Code unit / e2e tested and comply with QWASP
- [x] No new security vulnerabilities 
- [x] Flexion code review
- [x] Documentation / readme.md updated
- [x] Docker updated
- [x] Visual design review
- [ ] Usability tested

Tasks
- [x] Design / UX: Copy
- [x] Design / UX: 18F approves copy
- [x] Server: Create email template
- [x] Server: Trigger email when application status is set to 'returned'

**Comment by colinpmacarthur** [comment]
This story only covers what happens when applications are flatly rejected (not put on hold for revision). Email notifications for "holding for revision" are covered by story #844.

**Comment by npage123** [comment]
Temp outfitter email text:

Subject Line: An update on your recent permit application to the Forest Service.


Permit application status update
*********************************

Unfortunately the following permit application has not been accepted.

——Admin custom message inserted here—— 


Application details
*********************************

Business name:
Start date:
End date:
Number of trips:
Number of participants:
Services:

If you would like to submit another permit application visit https://fs-intake-staging.app.cloud.gov/.

Contact us
*********************************

If you have questions or need to contact the permit staff at the National Forest Service, please use a method listed below.

Temp outfitter contact
Name: 
Title:
Phone:
Email:

Thank you for your interest in our National Forests.

Noncommercial email text:

Subject Line: An update on your recent permit application to the Forest Service.


Permit application status update
*********************************

Unfortunately the following permit application has not been accepted.

——Admin custom message inserted here—— 


Application details
*********************************

Event name:
Start date:
End date:
Number of participants:
Number of spectators:
Location:

If you would like to submit another permit application visit https://fs-intake-staging.app.cloud.gov/.

Contact us
*********************************

If you have questions or need to contact the permit staff at the National Forest Service, please use a method listed below.

Temp outfitter contact
Name: 
Title:
Phone:
Email:

Thank you for your interest in our National Forests.
