### ISSUE TITLE
As a Forest Service special uses administrator, when the application is accepted, explaining what will happen next. Permits are not “approved” until a later stage; this intake module would only handle processing applications from receipt to “acceptance,” while SUDS handles the rest of the process.

### ISSUE THREAD

**Issue by dubharmonic** [flexion/fs-intake-module#161]
Definition of Done
- [x] Code unit / e2e tested and comply with QWASP
- [x] No new security vulnerabilities 
- [x] Flexion code review
- [x] Documentation / readme.md updated
- [x] Docker updated
- [x] Visual design review
- [x] Usability tested

Tasks
- [x] Nate & Peter pair on planning
- [x] Review with Colin
- [x] Implement changes to the code

**Comment by lauraGgit** [comment]
Looks like this may be linked to #140.

**Comment by dubharmonic** [comment]
There needs to be an email to the applicant upon acceptance, and we need to remind them what this means.

**Comment by dubharmonic** [comment]
Admin clicks accept, is able to add a custom message. Email is sent to the applicant with the status change and the custom message.

The app should provide a default message.
