### ISSUE TITLE
Validation fails when tabbing through time fields

### ISSUE THREAD

**Issue by colinpmacarthur** [flexion/fs-intake-module#224]
When I tab through a time field set, the minute field validates, even if I leave it empty:

![screen recording 2017-05-16 at 06 29 pm](https://cloud.githubusercontent.com/assets/2092076/26131068/c1e7f316-3a65-11e7-9672-45d322eea550.gif)

**Comment by dubharmonic** [comment]
Looks to have been fixed by another change.
