### ISSUE TITLE
Left over development text?

### ISSUE THREAD

**Issue by colinpmacarthur** [flexion/fs-intake-module#226]
I assume this probably shouldn't be in the application form any more?
<img width="475" alt="screen shot 2017-05-16 at 6 32 55 pm" src="https://cloud.githubusercontent.com/assets/2092076/26131122/1f334a20-3a66-11e7-931a-ca8985699262.png">

**Comment by dubharmonic** [comment]
This was a placeholder for help text that was added yesterday by @pvd-flexion
