### ISSUE TITLE
Look into why the vertical red bar on input validations

### ISSUE THREAD

**Issue by sethalt** [flexion/fs-intake-module#227]
There should be a red vertical indicator to the left of an input when there is an error. It may or may not be necessary, but John should give the final say.

![screen shot 2017-05-17 at 9 51 33 am](https://cloud.githubusercontent.com/assets/2347759/26160402/c81ee588-3ae6-11e7-9946-74a07e027565.png)

Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities 
- [ ] Flexion code review
- [ ] Documentation / readme.md updated
- [ ] Docker updated
- [ ] Visual design review
- [ ] Usability tested

**Comment by lauraGgit** [comment]
@dubharmonic can this be closed?
