### ISSUE TITLE
add .cfignore

### ISSUE THREAD

**Issue by lauraGgit** [flexion/fs-intake-module#250]
speed up app restaging by adding a .cfignore of what to not upload to cloud.gov.

**Comment by dubharmonic** [comment]
@lauraGgit based on what I can tell from our deploy scripts there aren't any unnecessary directories being uploaded, though without cloud.gov access I can't verify that. Are there any specific directories or files that should be ignored?

**Comment by lauraGgit** [comment]
yeah that is probably true
