### ISSUE TITLE
As a permit applicant, I want to receive a confirmation email after submitting an application to keep for my records.

### ISSUE THREAD

**Issue by npage123** [flexion/fs-intake-module#263]
Definition of Done
- [x] Code unit / e2e tested and comply with QWASP
- [x] No new security vulnerabilities 
- [x] Flexion code review
- [x] Documentation / readme.md updated
- [x] Docker updated
- [x] Visual design review
- [ ] Usability tested

Tasks
- [x] Server: add VCAP_SERVICES values for email server
- [x] Server: parse VCAP_SERVICES values for email server (Eric)
- [x] Server: find and implement SMTP node module (Seth & Eric)
- [x] Server: find template library for adding dynamic values
- [x] Design: Decide on HTML or text
- [x] Design: Mockups (Peter & Nate)
- [x] Design / UX: Copy (Peter & Nate)
- [x] Design / UX: 18F approves email content (Colin, Peter & Nate)

**Comment by dubharmonic** [comment]
Printing CSS available for confirmation screens.

**Comment by dubharmonic** [comment]
Same event as sending an email to the admin.

**Comment by dubharmonic** [comment]
Include next steps, link to application for review (after logging in), summary of event.

**Comment by dubharmonic** [comment]
Includes most of the same things that the confirmation page includes, along with a subset of application information (Permit type, event name). This is for all permit types.

Text email for this story, make a new story for HTML email.

ID number will be part of a different story.

**Comment by npage123** [comment]
@thegoldentoilet @sethalt  - So there are two different texts, one for temp outfitter and one for noncommercial. Please see below. 


Temp Outfitter Email Subject Line: Your temporary outfitter permit application has been submitted for review.

Text:
Submitted for review!
*********************

Your permit application has been submitted for review, but is NOT APPROVED until you hear from a special use administrator. Submitting an application does not guarantee your permit will be approved. 


Application details
*********************

Business name:
Start date:
End date:
Number of trips:
Number of participants:
Services:


What happens next?
*********************

1. Your application will be reviewed by our staff.
2. If additional information is needed, a representative of the National Forest Service will contact you via email to resolve any issues.
3. Once your application has been reviewed by our staff, you will be notified of the application status.
4. If your application is approved, you will receive your permit within 2 weeks of approval.


Contact us
*********************

If you have questions or need to contact the permit staff at the National Forest Service, please use a method listed below.

Temp outfitter contact
Name: 
Title:
Phone:
Email:

Thank you for your interest in our National Forests.



Noncommercial Email Subject Line: Your noncommercial permit application has been submitted for review!

Text:
Submitted for review!
*********************

Your permit application has been submitted for review, but is NOT APPROVED until you hear from a special use administrator. Submitting an application does not guarantee your permit will be approved. 


Application details
*********************

Event name:
Start date:
End date:
Participants:
Spectators:
Location: 


What happens next?
*********************

1. Your application will be reviewed by our staff within 48 hours.
2. If additional information is needed, a representative of the National Forest Service will contact you via email to resolve any issues.
3. Once your application has been reviewed by our staff, you will be notified of the application status.
4. If your application is approved, you will receive your permit via U.S. mail within 2 weeks of approval.


Contact us
*********************

If you have questions or need to contact the permit staff at the National Forest Service, please use a method listed below.

Noncommercial contact
Name:
Title:
Phone:
Email:

Thank you for your interest in our National Forests.
