### ISSUE TITLE
As a Forest Service special uses administrator, I would like to be able to view recorded revisions of an application to keep a better track of changes to it.

### ISSUE THREAD

**Issue by npage123** [flexion/fs-intake-module#283]
Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities 
- [ ] Flexion code review
- [ ] Documentation / readme.md updated
- [ ] Docker updated
- [ ] Visual design review
- [ ] Usability tested

**Comment by dubharmonic** [comment]
Duplicate of #303
