### ISSUE TITLE
As a Forest Service special uses administrator, I would like to be able to upload documents to add to a permit application.

### ISSUE THREAD

**Issue by npage123** [flexion/fs-intake-module#284]
Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities 
- [ ] Flexion code review
- [ ] Documentation / readme.md updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by dubharmonic** [comment]
Beyond scope.
