### ISSUE TITLE
As a special use administrator, I would like to be able to see an application revision history.

### ISSUE THREAD

**Issue by colinpmacarthur** [flexion/fs-intake-module#303]
Acceptance criteria
- [x] display history of status changes with datetime and actor

Definition of Done
- [x] Code unit / e2e tested and comply with QWASP
- [x] No new security vulnerabilities 
- [x] Flexion code review
- [x] Documentation / readme.md / CircleCI updated
- [x] Docker updated
- [x] Compare finished design with mockup
- [x] Usability tested

Tasks
- [x] Create mockup (Nate, Colin, Peter)
- [x] Create new table for revision history (Eric & Jesse)
- [x] Create new model for revision history (Eric & Jesse)
- [x] Create trigger for adding a row to revision history (Eric & Jesse)
- [x] Update API endpoints for revision history (Eric & Jesse)
- [x] Implement mockups in HTML & CSS (Seth & Chris)
- [x] Update view screens to show revision history (Seth & Chris)

**Comment by colinpmacarthur** [comment]
@npage123 @pvd-flexion -- added this following our discussion yesterday. cc: @dubharmonic

**Comment by npage123** [comment]
Mockups for reference:

An example of revision history in a pending application detail.
![application-revision-history-rd2-01](https://user-images.githubusercontent.com/12956624/31349224-fd412e06-ace7-11e7-9863-02f18d544db1.jpg)

An example of revision history in an accepted application detail.
![application-revision-history-rd2-02](https://user-images.githubusercontent.com/12956624/31349225-fd45c63c-ace7-11e7-88b5-2a41bbc89d3a.jpg)

An example of revision history in a rejected application detail.
![application-revision-history-rd2-03](https://user-images.githubusercontent.com/12956624/31349226-fd49c8cc-ace7-11e7-8c7a-b5b4953b9a58.jpg)

An example of revision history in a cancelled application detail.
![application-revision-history-rd2-04](https://user-images.githubusercontent.com/12956624/31349227-fd4b6d3a-ace7-11e7-9ade-75c3de8f0c9e.jpg)

**Comment by colinpmacarthur** [comment]
@npage123 Looks good!

Couple things:

- Can we show the "received" date in the status list?
- What does it look like when an application has just been received?

**Comment by npage123** [comment]
Regarding the bug discovered in sprint review, I have been unable to duplicate it since. Am going to assume it is something that came about while in zoom and sharing my screen.
<img width="485" alt="screen shot 2017-10-13 at 10 22 26 am" src="https://user-images.githubusercontent.com/12956624/31667069-f1863e3a-b313-11e7-8eb2-f476a53cb1d1.png">
