### ISSUE TITLE
PUT to SUDS is broken

### ISSUE THREAD

**Issue by sethalt** [flexion/fs-intake-module#389]
<img width="1269" alt="screen shot 2017-06-09 at 1 53 54 pm" src="https://user-images.githubusercontent.com/2347759/26990151-46305844-4d1b-11e7-862f-32c426c69a3d.png">

**Comment by dubharmonic** [comment]
a 500 error is currently being returned by the middle later API, we'll need help debugging

**Comment by sethalt** [comment]
@lauraGgit check into db error

**Comment by dubharmonic** [comment]
Error: `{"statusCode":500,"body":{"status":"error","message":"error while saving application in the database."},`

**Comment by dubharmonic** [comment]
Fixed!
