### ISSUE TITLE
As a temp outfitter, I would like to be able to add temp outfitter specific information to the temp outfitter’s permit applicant form

### ISSUE THREAD

**Issue by dubharmonic** [flexion/fs-intake-module#418]
This task only includes the simpler fields, not the more complex fields, which have their own stories.

Definition of Done
- [ ] Acceptance criteria met (UAT)
- [ ] Code refactored for clarity
- [ ] Framework code decoupled from ours
- [ ] Source code committed
- [ ] Unit test coverage of our code = 100%
- [ ] Code reviewed (or developed by pair)
- [ ] Security reviewed and reported
- [ ] No local design debt
- [ ] Build process updated
- [ ] Source documentation generated
- [ ] API documentation generated
- [ ] Code quality checks passed
- [ ] Guides and training draft updated
- [ ] Security & privacy gates passed

**Comment by rrefoy** [comment]
question here - the spacing seems a bit odd on the form. Does the main column have to be so skinny? I think some places in the form it doesn't make sense (to me) to have the text in a strict column that is the same width as say the dates and times section of the form. Curious what Colin thinks as well. Something to keep in mind when doing user testing.

**Comment by dubharmonic** [comment]
the width comes straight from the standards here: [](https://standards.usa.gov/components/form-controls/)

If there's space to the right, a progress widget will be shown.
