### ISSUE TITLE
Date validation

### ISSUE THREAD

**Issue by colinpmacarthur** [flexion/fs-intake-module#434]
When I enter this set of apparently valid dates:

<img width="292" alt="screen shot 2017-06-14 at 4 29 34 pm" src="https://user-images.githubusercontent.com/2092076/27154272-6ea28ba2-5122-11e7-92f6-4deb35f01ad3.png">

I receive this set of errors:

<img width="487" alt="screen shot 2017-06-14 at 4 29 39 pm" src="https://user-images.githubusercontent.com/2092076/27154244-59909ee8-5122-11e7-8278-7d7fb9d32102.png">

**Comment by dubharmonic** [comment]
The values being sent to the server appear to be in the correct format: `startDateTime:"2018-03-19T12:30:00Z"` and `endDateTime: "2018-03-22T16:30:00Z"`

The issue seems to be incorrect server-side validation.
