### ISSUE TITLE
When there's a validation error, fields still have green outline

### ISSUE THREAD

**Issue by colinpmacarthur** [flexion/fs-intake-module#435]
Even when a validation error appears at the top of the page...

<img width="486" alt="screen shot 2017-06-14 at 4 27 02 pm" src="https://user-images.githubusercontent.com/2092076/27154324-a8316b0e-5122-11e7-8000-813ee4fef104.png">

...the fields retain their green outline.

<img width="238" alt="screen shot 2017-06-14 at 4 28 41 pm" src="https://user-images.githubusercontent.com/2092076/27154327-ace4ec2a-5122-11e7-96e8-6778f21d04df.png">

**Comment by dubharmonic** [comment]
This was caused by the faulty regex on the server, which has been fixed.
