### ISSUE TITLE
Changes to Application detail page from User Testing 6/22-23/2017

### ISSUE THREAD

**Issue by pvd-flexion** [flexion/fs-intake-module#488]
Fix scrolling issue. Application Detail page loads at the scrolled location of the previous page.

Allow an admin to assign and alert another admin to a specific application.

Review and change names of three main button, Accept, Hold and Return. Consider addition of descriptions.

Add "Hold" indicator on the Application Detail page.

Email functionality added to three mail buttons on Application Detail page.
**Accept:** 
- Send an email to applicant informing them that the application has been accepted and what that means.
- Allow the admin to add notes or comments.
- Include next steps and timeline.
- Include the admin's name and contact info.
- If accepted application become available in a separate view within the admin system, document the Accepted confirmation message content, date and admin.

**Hold:**
- Send an email to applicant informing them that the application has been put on hold and what that means.
- Allow the admin to add info about why the application was out on hold and request the additional information required to clear up the issue.
- Include the admin's name and contact info.
- Document "Hold" communication dates sent, message content, admin sending on Application detail page.

**Return:**
- Send an email to applicant informing them that the application has been rejected and what that means
- Allow the admin to add information about why it was returned
- Include the admin's name and contact info.
- If Returned application become available in a separate view within the admin system, document the Returned confirmation message content, date and admin.

**Comment by npage123** [comment]
Proposed pattern for sending user feedback and changing status of application

• User selects a CTA
![admin-detail-mockup-desktop-rd7](https://user-images.githubusercontent.com/12956624/27559707-2b8e6d22-5a87-11e7-816a-b2d38f09056f.jpg)

• For example, user selects the "Hold" button, sticky button bar changes to text input where admin can type up reasons for on hold and then send to the user which will also change the status of the application to On Hold. Admin has the option to cancel or close which will take that view back to the button bar.
![admin-detail-hold-mockup-desktop-rd7](https://user-images.githubusercontent.com/12956624/27559829-98488434-5a87-11e7-89e1-c9ba9447dd8d.jpg)
