### ISSUE TITLE
Changes to Application List Page From User Testing 6/22-23/2017

### ISSUE THREAD

**Issue by pvd-flexion** [flexion/fs-intake-module#489]
Add alert message when an application has been in the system over 48 hours without being accepted or had issues addressed

Generate email to appropriate admins when an application has been in the system over 48 hours without being accepted or had issues addressed

**Comment by dubharmonic** [comment]
@pvd-flexion what should the alert message say, and where should it be located?

**Comment by dubharmonic** [comment]
Yellow warning message at the top, offending applications get a yellow triangle icon next to them (like hold does) 

Message text:
