### ISSUE TITLE
“Skip to Main Content” link always goes to the Home page

### ISSUE THREAD

**Issue by JohnHewittCriterion** [flexion/fs-intake-module#496]
When using keyboard navigation, the “Skip to Main Content” link in the header should bypass the navigation on the current page to the first focusable element in that page’s main content area.
On every page in the ePermit staging site, the “Skip to Main Content” link goes to the first focusable element on the Home page. This is correct on the Home page, but its occurrence on all interior pages renders the “Skip to Main Content” link useless.
This occurs because the <base> href is set to “/” in the <head> section. The target of the “Skip to Main Content” link is “#main-content”. Since the target of the “Skip to Main Content” link does not specify a page, the browser defaults to the <base> href, taking the user to the main content section of the Home page.
See http://www.w3.org/WAI/WCAG20/quickref/#qr-navigation-mechanisms-skip.

WCAG: 2.4 Navigable - 2.4.1 Bypass Blocks 
S-508: 1194.22 (o) 
LINK: EPERM-35

**Comment by JohnHewittCriterion** [comment]
Does scroll the page, but the focus doesn't move. 
Not sure why href is:
   #/applications/temp-outfitters/new#main-content
     not
  #main-content but that could be causing the problem.
It should after hitting enter move the focus down the page so the next time you hit TAB it goes to the first input box.  This may be due to the dynamic nature of the page.

**Comment by sethalt** [comment]
We are working on removing the first # from the url in the hope that this will correct our issue.

**Comment by JohnHewittCriterion** [comment]
There is still an issue.  I'm not sure if the page isn't fully rendered, or some other issue, but if I use keyboard only it doesn't jump to the location.  However if I hit F12 to bring up the developer mode, it seems to work.

**Comment by JohnHewittCriterion** [comment]
Still an issue.  Steps to reproduce:
1) to go https://fs-intake-staging.app.cloud.gov/
2) Tab to "Skip to Main Content"
3) Press space (notice page scrolls)
4) Tab still now moves back to the top "Here's how you know" link instead of into "Noncomercial permit" button.
