### ISSUE TITLE
The Choose File fields on the "Apply for a temp outfitters permit" page do not show visible focus indication

### ISSUE THREAD

**Issue by JohnHewittCriterion** [flexion/fs-intake-module#513]
The Choose File fields on the "Apply for a temp outfitters permit" page do not show visible focus indication. As the user tabs through the page, there is no focus indication for any of the Choose File form fields. The same issue exists for the Replace button. The Remove button does have focus indication.

![image](https://user-images.githubusercontent.com/28604890/27606191-4c574e5e-5b4d-11e7-8503-db457f8c62e4.png)

WCAG: 2.4 Navigable - 2.4.7 Focus Visible
S-508: 1194.21 (c) 
LINK: EPERM-51

**Comment by JohnHewittCriterion** [comment]
The focus indicator and the background have a contrast Ratio of 1.9.  This would leave the focus indicator not visible to many users.  The guidelines for success are listed here: http://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-focus-visible.html
However, I've found just inverted the colors for buttons on Hover and Focus give a consistent feel for both mouse and keyboard only users.

**Comment by npage123** [comment]
@JohnHewittCriterion - Checking to see if this is similar to #515 which you ok'd yesterday? I believe the same focus color is used.

**Comment by JohnHewittCriterion** [comment]
On IE: The buttons are now a dark brown color and have a light blue focus border but it is very hard to see. They also require two presses of the tab key to move focus to the next focusable item on the page. On Firefox: There is no focus indication shown at all. The tabbing to the next focusable items worked correctly; only requiring one press of the tab key to move focus through these buttons. On Chrome: The buttons are now a dark brown color and have a light blue focus border but it is very hard to see. The tabbing to the next focusable items worked correctly; only requiring one press of the tab key to move focus through these buttons.
