### ISSUE TITLE
On the Apply for a permit page, the focus indication around the buttons is very faint

### ISSUE THREAD

**Issue by JohnHewittCriterion** [flexion/fs-intake-module#515]
On the Apply for a permit page, the focus indication around the buttons is very faint. The buttons have a blue border upon focus. This is barely seen due to the background images having dark colors that drown out the focus indication contrast. Contrast ratio should be 3:1.

![image](https://user-images.githubusercontent.com/28604890/27606410-20e8f38e-5b4e-11e7-9e2c-a83b560a838a.png)

WCAG: 2.4 Navigable - 2.4.7 Focus Visible 
S-508: 1194.21 (c) 
LINK: EPERM-52

Tasks
- [x] copy fix from design standards dev branch
- [x] add fix to a dedicated sass file to be imported to the app
- [x] document fix in the readme explaining the issues
- [x] create a cleanup task for the product backlog to remind future us to instead use the new version of the standards

**Comment by dubharmonic** [comment]
Waiting for feedback from @JohnHewittCriterion

**Comment by JohnHewittCriterion** [comment]
New focus indication is still barely visible.  

I tested changing the style : .forest-service .usa-button-inverse:hover, .forest-service .usa-button-inverse:hover:visited
to
.forest-service .usa-button-inverse:hover, .forest-service .usa-button-inverse:hover:visited, .forest-service .usa-button-inverse:focus
To include focus, and how the keyboard only users will get the same look/feel as the mouse users.  Generally it's a good idea to have :hover and :focus be the same.

![image](https://user-images.githubusercontent.com/28604890/29427134-e7552a1c-8356-11e7-80f5-28a28a3e7f62.png)

**Comment by colinpmacarthur** [comment]
This is going to be addressed upstream by a change to the web design standards: https://github.com/18F/web-design-standards/pull/2112

@sethalt: Should we close this for now? Keep it open until we merge in the upstream changes?

**Comment by sethalt** [comment]
I'd prefer to keep it open as a reminder to update web design standards when this change is made.
