### ISSUE TITLE
As a temp outfitter I would like to have a positive, intuitive experience in completing the temp outfitter’s permit applicant form

### ISSUE THREAD

**Issue by dubharmonic** [flexion/fs-intake-module#572]
User testing and modifications to the application based on the results.

**Comment by dubharmonic** [comment]
User tests are starting today.

**Comment by npage123** [comment]
Stories created from usability testing:
https://github.com/flexion/fs-intake-module/issues/719
https://github.com/flexion/fs-intake-module/issues/718
https://github.com/flexion/fs-intake-module/issues/717
https://github.com/flexion/fs-intake-module/issues/716
https://github.com/flexion/fs-intake-module/issues/715
https://github.com/flexion/fs-intake-module/issues/714
https://github.com/flexion/fs-intake-module/issues/713
https://github.com/flexion/fs-intake-module/issues/712
https://github.com/flexion/fs-intake-module/issues/711
