### ISSUE TITLE
As a temp outfitter I would like to know where I am in the temp outfitter's form via a left nav.

### ISSUE THREAD

**Issue by dubharmonic** [flexion/fs-intake-module#584]
https://github.com/flexion/fs-intake-module/commit/34f4e01a656c641fa2d3a3235c4861b139d33560

Definition of Done
- [x] Code unit / e2e tested and comply with QWASP
- [x] No new security vulnerabilities 
- [x] Flexion code review
- [x] Documentation / readme.md updated
- [x] Docker updated
- [x] Visual design review
- [x] Usability tested
- [x] Deployed to staging

**Comment by npage123** [comment]
Please use this updated mockup - https://github.com/flexion/fs-intake-module/commit/34f4e01a656c641fa2d3a3235c4861b139d33560

**Comment by sethalt** [comment]
Is it possible to add spacing between the left nav and form to match that of the following example?
https://standards.usa.gov/components/

**Comment by sethalt** [comment]
Left nav overlapping footer: <img width="1214" alt="screen shot 2017-08-15 at 8 13 17 am" src="https://user-images.githubusercontent.com/12956624/29317500-ca24804e-8191-11e7-96ae-211bc3633b51.png">

**Comment by sethalt** [comment]
If on any step beyond step 2 in the left nav, then clicking on step 2, it jumps to step 1. Click on step 3 and any step beyond step 3, then click on step 2, you'll see that the left nav jumps to step 1.

**Comment by sethalt** [comment]
Please change the color of the border dividing lines between nav items from #5b616b to the hint text color #656565.

**Comment by sethalt** [comment]
@npage123 please review this and confirm that it is completed to your specifications

**Comment by npage123** [comment]
@sethalt - Looks like the border color is still using the standards color? Should be #656565.

**Comment by npage123** [comment]
@sethalt - With the advertising section now optional, should that item in the left nav function like the other optional sections where after scrolling by the first time it marks it as checked? And also, with guide identification now being optional, that should probably function the same way.

**Comment by npage123** [comment]
- [x] Left nav scrolls into the footer on a wide shortened browser window.
