### ISSUE TITLE
As a temp outfitter applicant I would like to be informed of the next steps after I successfully submit my application.

### ISSUE THREAD

**Issue by dubharmonic** [flexion/fs-intake-module#594]
Definition of Done
- [x] Code unit / e2e tested and comply with QWASP
- [x] No new security vulnerabilities 
- [x] Flexion code review
- [x] Documentation / readme.md updated
- [x] Docker updated
- [x] Visual design review
- [x] Usability tested

**Comment by dubharmonic** [comment]
"What Happens Next" needs to be sentence case

**Comment by sethalt** [comment]
@npage123 please review this page and confirm that it has been completed to your specifications.

**Comment by npage123** [comment]
@sethalt - Should the Contact Us headline have a lowercase u in "us"?

**Comment by dubharmonic** [comment]
Do the status labels make sense to the users? Is it clear that they haven't been rejected or approved?
