### ISSUE TITLE
As a noncommercial applicant, I would like to be informed that noncommercial permits are free.

### ISSUE THREAD

**Issue by dubharmonic** [flexion/fs-intake-module#642]
Definition of Done
- [x] Code unit / e2e tested and comply with QWASP
- [x] No new security vulnerabilities 
- [x] Flexion code review
- [x] Documentation / readme.md updated
- [x] Docker updated
- [x] Visual design review
- [x] Usability tested

**Comment by npage123** [comment]
Please change the Non-commercial permit description to the following:

"For a non-commercial activity involving a group of 75 or more people, either as participants or spectators with no entry/participation fee. The primary purpose of the event isn’t selling goods or services. This type of permit is free."

**Comment by dubharmonic** [comment]
Feedback
* Ask users how much the permit type costs in usability testing
* This is implicit in the wizard
