### ISSUE TITLE
Application submitted page copy

### ISSUE THREAD

**Issue by sethalt** [flexion/fs-intake-module#649]
Remove dummy copy and add real copy in place.

**Comment by sethalt** [comment]
![screen shot 2017-07-27 at 10 03 49 am](https://user-images.githubusercontent.com/2347759/28678364-cf42dab6-72b5-11e7-8f31-d6099831eaff.png)

**Comment by npage123** [comment]
• New story will be created to discuss the buttons at the bottom down the road. Decision made to take them out for now. All content below the text "Thank you for your interest...." remove. 

• Temp outfitter contact information is ok as is for now and will be adjusted when in production.

**Comment by sethalt** [comment]
Great! I'll make the updates and commit.
