### ISSUE TITLE
As a temp outfitter I would like to understand why I need to enter specifics around client charges.

### ISSUE THREAD

**Issue by npage123** [flexion/fs-intake-module#662]
Acceptance Criteria
- [ ] add details to learn more screen

Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities 
- [ ] Flexion code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

Tasks
- [x] Add detail to the form description in application (Nate & Peter)
- [x] Review form description in application (Nate, Colin & Peter)
- [ ] Implement added detail (Eric)

**Comment by colinpmacarthur** [comment]
I think this should be a pre-demo priority.

**Comment by dubharmonic** [comment]
Specifically ask about this in usability testing - @pvd-flexion

**Comment by npage123** [comment]
Blocked in that it questions are being asked about it in usability testing. Will have a better idea of what the verbiage should be after Wednesday the 11th.

**Comment by npage123** [comment]
Mockup to reference:
<img width="495" alt="screen shot 2017-10-12 at 2 55 15 pm" src="https://user-images.githubusercontent.com/12956624/31516322-d0ed8a8e-af5d-11e7-8051-34ebce4a4649.png">

Text to copy/paste:
Provide a description of client charges and fees and what they cover (account for any additional fees, scholarships, etc.).
What you enter will not change what you will be charged. Charges for a temporary outfitter permit are based on a flat rate (see costs on the learn more page).

**Comment by npage123** [comment]
In usability testing this week we received feedback from both guides and special use admin on the client charges portion of the temp outfitter application. Most guides again questioned why this info is needed and unsure what details to enter. There was concern that what they enter might affect what they are charged for using the forest and how that would work if only a small amount of time from the class is spent in the forest (majority spent in a classroom). The special use admin were not as concerned with the information needed. Stated its more for a reference, or to make sure they are not marking the price up too much. Sue mentioned it has no effect on what the guide is charged because temp outfitter applications are based on a flat rate fee. So with that, a description has been added to the form to better explain to the guides what this information is used for and we feel a description is no longer needed in the temp outfitter learn more page
