### ISSUE TITLE
As a temp outfitter I want to understand what the guide identification requirements are at the time of submission.

### ISSUE THREAD

**Issue by npage123** [flexion/fs-intake-module#663]
Definition of Done
- [x] Code unit / e2e tested and comply with QWASP
- [x] No new security vulnerabilities 
- [x] Flexion code review
- [x] Documentation / readme.md updated
- [x] Docker updated
- [x] Visual design review
- [x] Deployed to staging
- [x] Usability tested

Discuss with special use admins on what specific information is wanted and how it should be provided. Is it possible to put hiring requirements in here and would those be enough for the special use admins to make a decision.

**Comment by colinpmacarthur** [comment]
I think this should be a pre-demo priority.

**Comment by npage123** [comment]
All users were concerned about having this information ready when applying and how it would be uploaded at the same time. All users had large numbers of files for each guide. One user had a spreadsheet they created for this requirement that stored all guide info and qualifications.

Suggestion
Create a spreadsheet template for guide info (certifications, confirmation numbers, etc.) Then, SUAs can ask for additional proof of certification if they feel it is needed based on the trip details.

Also allow users to enter an overview of their guide qualification requirements and training instead of uploading the guide info spreadsheet. This should include instructions that the guide info will be required later in the approval process.

All users and SUAs were positive about the idea of a Guide Database. This would allow professional guides to manage a profile themselves that is kept updated, along with qualifications, training and certification status. Then an organization could just attach particular guides from the database, instead of building and managing this info for every single permit application.

**Comment by npage123** [comment]
Use existing template from usability testing outfitter. Provide download link and upload functionality.

**Comment by npage123** [comment]
1. Use the following text: 

• Attach a list of all guides who would be working under the permit.

• Describe your requirements for employment and staff training programs.

• Attach copies of current CPR and First Aid certifications, Wilderness First Responder cards, and other applicable certifications for guides. Please do not send copies of social security cards or passports. Send driver’s licenses only if driving is part of the outfitting and guiding service.

• If the state in which your activity would occur requires licensing for outfitters and guides, include a copy of relevant licenses.
File must be in .pdf, .doc, .docx., or .rtf format, and less than 25MB.

If you do not have these guide details yet, it is not required at this step in the application process but know that these details will need to be provided eventually to move through the application process. 

If you need a guide identification template, click here to download one.

2. Mark the upload field as (optional).

3. Add template.

**Comment by npage123** [comment]
- [ ] Include .xlxs file type in file upload description
