### ISSUE TITLE
As a temp outfitter, I'd like to know what types of citations I need to document.

### ISSUE THREAD

**Issue by sethalt** [flexion/fs-intake-module#667]
Talk to special use admins to discuss whether all citations need to be documented, or just specific types of citations.

Aaron is gathering more info on acceptance criteria. 

Acceptance Criteria
- [x] update learn more screen and form copy to specify the last 3 years, other permits in other areas, no limits on citations to include?

Tasks
- [x] Add text to template (Eric)
- [x] Move text on template (Eric)

Definition of Done
- [x] Code unit / e2e tested and comply with QWASP
- [x] No new security vulnerabilities 
- [x] Flexion code review
- [x] Documentation / readme.md / CircleCI updated
- [x] Docker updated
- [x] Compare finished design with mockup
- [ ] Usability tested

**Comment by dubharmonic** [comment]
Add to the hint text? We should talk to the special use admins.

**Comment by colinpmacarthur** [comment]
@npage123 @pvd-flexion Is this a usability testing issue?

**Comment by npage123** [comment]
@colinpmacarthur @pvd-flexion - I think it was Colin. Will add a label.

**Comment by colinpmacarthur** [comment]
Please add the following hint text to this section:

> Answers to this and other questions are used to assess whether you have "the financial or technical capability to undertake the use and to fully comply with the terms and conditions of the authorization."

**Comment by colinpmacarthur** [comment]
@sethalt Would it be possible to make the explanatory text visible _before_ people click the checkbox? I think they're trying to decide whether or not to check the box.

**Comment by dubharmonic** [comment]
@npage123 can you help us with where to put the hint? I don't think we have any other situations like this one.

<img width="1243" alt="screen shot 2017-10-24 at 12 30 49 pm" src="https://user-images.githubusercontent.com/248694/31958591-e7569f0a-b8b7-11e7-848c-b9374719b25f.png">

**Comment by npage123** [comment]
I'm thinking that description would be best located under the "Experience" section head. But would need to be re-worded to read something like "Answers to the following questions are used to assess whether you have "the financial or technical capability to undertake the use and to fully comply with the terms and conditions of the authorization." @dubharmonic. @colinpmacarthur - Thoughts?
