### ISSUE TITLE
As a special use administrator I want applicants to better understand what’s required or isn’t required by the temp outfitter permit application.

### ISSUE THREAD

**Issue by dubharmonic** [flexion/fs-intake-module#673]

**Comment by npage123** [comment]
Stories created from usability testing:
https://github.com/flexion/fs-intake-module/issues/719
https://github.com/flexion/fs-intake-module/issues/718
https://github.com/flexion/fs-intake-module/issues/717
https://github.com/flexion/fs-intake-module/issues/716
https://github.com/flexion/fs-intake-module/issues/715
https://github.com/flexion/fs-intake-module/issues/714
https://github.com/flexion/fs-intake-module/issues/713
https://github.com/flexion/fs-intake-module/issues/712
https://github.com/flexion/fs-intake-module/issues/711
