### ISSUE TITLE
As a public user, I want to be sure that the servers I’m logging into are the genuine intake application and login.gov.

### ISSUE THREAD

**Issue by dubharmonic** [flexion/fs-intake-module#675]
Definition of Done
- [x] Code unit / e2e tested and comply with QWASP
- [x] No new security vulnerabilities 
- [x] Flexion code review
- [x] Documentation / readme.md updated
- [x] Docker updated
- [ ] Usability tested

**Comment by npage123** [comment]
@dubharmonic will add a mock for the identity provider and cleanup the description since were not using SAML anymore.

**Comment by dubharmonic** [comment]
Ready for usability testing
