### ISSUE TITLE
As an applicant I want to be able to logout of the intake application.

### ISSUE THREAD

**Issue by dubharmonic** [flexion/fs-intake-module#677]
Definition of Done
- [x] Code unit / e2e tested and comply with QWASP
- [x] No new security vulnerabilities 
- [x] Flexion code review
- [x] Documentation / readme.md updated
- [x] Docker updated
- [x] Visual design review
- [x] Usability tested

Tasks
- [x] Client: Logout confirmation message
- [x] Are we logging out of both the intake application and login.gov?
- [x] Hit logout endpoint for login.gov when logging out

**Comment by dubharmonic** [comment]
Need a logout API end point connected to passport.

**Comment by dubharmonic** [comment]
Logging out of login.gov and the intake app.

**Comment by npage123** [comment]
@dubharmonic - Please make the logged out alert messaging text "You have successfully logged out of Forest Service permits."

**Comment by colinpmacarthur** [comment]
Small thing -- I think the wording in the upper menu bar should be "Log out" not "Logout"
