### ISSUE TITLE
As an applicant I want to be sure that all of my file attachments have uploaded successfully before my application has been submitted.

### ISSUE THREAD

**Issue by sethalt** [flexion/fs-intake-module#699]
Acceptance Criteria
- [x] Show a success screen only after complete success
- [x] Uploading files interstitial progress indicator
- [x] If uploads are not successful, go back to the application and show an error message as soon as possible

Currently, a user is sent to the submitted screen while files are still uploading. We need to listen for file upload completion before sending a user on.

Definition of Done
- [x] Code unit / e2e tested and comply with QWASP
- [x] No new security vulnerabilities 
- [x] Flexion code review
- [x] Documentation / readme.md / CircleCI updated
- [x] Docker updated
- [x] Compare finished design with mockup
- [x] Usability tested

Tasks
- [x] Create a progress indicator screen design (Peter, Nate & Colin)
- [x] Create a progress indicator screen (Seth & Chris)
- [x] Event handler for file upload completion  (Seth & Chris)

**Comment by npage123** [comment]
Link to page sent by Colin for code reference (last option on page) - https://www.projectcorsair.com/extended/progress-bars

Please use mockup for reference - ![progress-indicator-rd2-01](https://user-images.githubusercontent.com/12956624/31194582-33ec703e-a90d-11e7-9049-3cc04c24acb8.jpg)

**Comment by npage123** [comment]
We'll need to figure out how to handle an error in the file upload.
