### ISSUE TITLE
As a temp outfitter, I would like to be aware that I don't need to provide an operating plan at this point in the application process but eventually will need to.

### ISSUE THREAD

**Issue by npage123** [flexion/fs-intake-module#717]
Definition of Done
- [x] Code unit / e2e tested and comply with QWASP
- [x] No new security vulnerabilities 
- [x] Flexion code review
- [x] Documentation / readme.md updated
- [x] Docker updated
- [x] Usability tested
- [x] Visual design review

Most users were concerned about this being ready before they knew they had an approved permit. Most users said that creating an operating plan was part of their trip planning process.

They use it for purposes other than solely the permit requirement (e.g., guide training, client communication, etc.) So, uploading this file would not be an issue, but being able to do it later in the process would be preferable.

**Suggestion**
Create a more complete, easier-to-use template for the operating plan. Allow users to include a
description of important parts of the operating plan in the form instead of requiring it for initial
application submission. Clearly indicate that while the user can submit the application without an
operating plan, they must provide one before having their application approved.

**Comment by npage123** [comment]
1. Change text under Operating Plan heading text to read:

Attach an operating plan that addresses client and visitor safety, evacuation and emergency procedures, and resource protection with respect to your proposed operations and location.

If you do not have the operating plan finalized yet, it is not required at this step in the application process but know that one will need to be provided eventually to move through the application process.

If you need an operating plan template, click here to download one.

File must be in .pdf, .doc, .docx., or .rtf format, and less than 25MB.

2. Add "(optional)" above the file upload box.

**Comment by sethalt** [comment]
Changed text to:

An operating plan addresses client and visitor safety, evacuation and emergency procedures, and resource protection with respect to your proposed operations and location.

An operating plan is not required to apply, but will be required before your application is approved.

If you need an operating plan template, click here to download one.

File must be in .pdf, .doc, .docx., or .rtf format, and less than 25MB.
