### ISSUE TITLE
As a user I want to be able to see the difference between "Log In" as a verb and "Login" as a noun.

### ISSUE THREAD

**Issue by dubharmonic** [flexion/fs-intake-module#729]
Definition of Done
- [x] Code unit / e2e tested and comply with QWASP
- [x] No new security vulnerabilities 
- [x] Flexion code review
- [x] Documentation / readme.md updated
- [x] Docker updated
- [x] Visual design review
- [ ] Usability tested

**Comment by colinpmacarthur** [comment]
I think we can exempt this issue from usability testing.
