### ISSUE TITLE
As a user I want to be informed of the 2 authentication options and be directed to the one that applies to me.

### ISSUE THREAD

**Issue by dubharmonic** [flexion/fs-intake-module#781]
Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities 
- [ ] Flexion code review
- [ ] Documentation / readme.md updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by npage123** [comment]
In a meeting with Colin, Peter, Chris and Nate we came to a conclusion that the best user experience for an admin to access applications should be a link within the special use admin intranet that currently exists. Alternatives that were discussed and vetoed were sending the admin a link where they would personally need to store it; and adding a link to the public intake interface which may confuse the public users. 

With the production url not finalized yet, this link should end with /admin/applications

**Comment by dubharmonic** [comment]
TODO: add Colin to the project

**Comment by dubharmonic** [comment]
Waiting on the FS
