### ISSUE TITLE
As an admin, I can view permit applications after authenticating to eAuth.

### ISSUE THREAD

**Issue by dubharmonic** [flexion/fs-intake-module#783]
Definition of Done
- [x] Code unit / e2e tested and comply with QWASP
- [x] No new security vulnerabilities 
- [x] Flexion code review
- [x] Documentation / readme.md updated
- [x] Docker updated
- [x] Visual design review
- [x] Usability tested
- [ ] Mocked strategy for tests

Tasks
- [x] Revisit after successfully implementing login.gov access control
- [x] Create a whitelist of users who can access applications
- [x] Handle a 403 response when a user doesn't have access
- [x] Route users to correct page after logging in and validate credentials

**Comment by dubharmonic** [comment]
The authentication response has no user name or email, what should we use to identify the user?

When anyone can register for an eAuth account, how do we filter FS admins?

**Comment by lauraGgit** [comment]
See #888 for including the authorizing official name in Noncommericial submissions to SUDS.
