### ISSUE TITLE
As an admin I would like to authenticate with my LincPass. (eAuth)

### ISSUE THREAD

**Issue by dubharmonic** [flexion/fs-intake-module#784]
The eAuth login will be linked to by the FS intranet.

Definition of Done
- [x] Code unit / e2e tested and comply with QWASP
- [x] No new security vulnerabilities 
- [x] Flexion code review
- [x] Documentation / readme.md updated
- [x] Docker updated
- [x] Visual design review
- [x] Usability tested

Tasks
- [x] Key in VCAP_SERVICES
- [x] Cert in VCAP_SERVICES
- [x] Issuer in VCAP_SERVICES
- [x] Entry Point in VCAP_SERVICES
- [x] Callback URL in VCAP_APPLICATION 
- [x] Callback URL registered
- [x] SAML Strategy created
- [x] eAuth specific routes
- [x] eAuth test accounts created
- [x] Set up page permissions based on role
- [x] Redirect to eAuth from admin pages
- [x] Write tests that validate the roles are working on the frontend.
- [x] Determine issues with integration

**Comment by lauraGgit** [comment]
https://docs.oracle.com/cd/E19681-01/820-4729/ggpgd/index.html

**Comment by dubharmonic** [comment]
related to #781
