### ISSUE TITLE
As a temp outfitter, I only want to enter my website address once in the temp outfitter form.

### ISSUE THREAD

**Issue by npage123** [flexion/fs-intake-module#791]
Please copy input entered into the Website field in the Applicant Information section of the temp outfitter form and reproduce it in the Website field in the Advertising section of the temp outfitter form. 

Acceptance Criteria
- [x] copy the value only when URL is valid

Definition of Done
- [x] Code unit / e2e tested and comply with QWASP
- [x] No new security vulnerabilities 
- [x] Flexion code review
- [x] Documentation / readme.md / CircleCI updated
- [x] Docker updated
- [x] Compare finished design with mockup
- [ ] Usability tested

Tasks
- [x] Modify trigger to fire only after validation (Seth)

**Comment by dubharmonic** [comment]
a valid address is required before copying
