### ISSUE TITLE
Non-Descriptive / Non-Unique Link Text

### ISSUE THREAD

**Issue by JohnHewittCriterion** [flexion/fs-intake-module#821]
Steps To Verify With JAWS:
 
Open the website and activate the "Temp outfitter's permit" link to move to the following URL: https://fs-intake-staging.app.cloud.gov/applications/temp-outfitters/new.
Open the links list box with the key combination Insert + F7.
Review to find a link labeled "click here". this does not give user a clear understanding of purpose and/or destination.

The page now has two links labeled "click here". When user presses the Tab key to move through the page components, the two "click here" links have spoken labels. However, with focus on the link, pressing Insert + Tab to hear the current focus, JAWS announces only 'click here'
 
Provide link text describing purpose and/or destination.

Links must have Unique Names.  There are several ways to resolve multiple "Click Here" links although the best is to have the text describe something unique that the link points to.

WCAG: 2.4 Navigable - 2.4.4 Link Purpose (In Context) 
Link: EPERM-86

Tasks:
- [ ] add an alt attribute to Click Here anchor tag (Chris)

**Comment by thegoldentoilet** [comment]
On the landing page updated text from: To learn more about a temporary outfitter's permit <a routerLink="/applications/temp-outfitters/faq">click here</a>.

to: <a routerLink="/applications/temp-outfitters/faq">Click here to learn more about a temporary outfitter's permit</a>.

**Comment by thegoldentoilet** [comment]
On the temp outfitters permit form updated from:   <p>If you need a guide identification template, <a href="/assets/files/guide-identification-template.xlsx" target="_blank">click here</a> to download one.</p>

to: <p>If needed, <a href="/assets/files/guide-identification-template.xlsx" target="_blank">click here to download a guide identification template</a>.</p>

and from: p>If you need an operating plan template, <a href="/assets/files/operating-plan-template.docx" target="_blank">click here</a> to download one.</p>

to: <p>If needed, <a href="/assets/files/operating-plan-template.docx" target="_blank">click here to download an operating plan template</a>.</p>

**Comment by npage123** [comment]
- [ ] Check with Mac Voice Over
- [ ] Check with JAWS

**Comment by npage123** [comment]
Checked issue with Mac Voice Over and links worked. However, noticed that the highlighted text in the screenshot below did not get read by the screen reader.
![asset 1-80](https://user-images.githubusercontent.com/12956624/30866754-bd92b6be-a29f-11e7-8656-480ec157ac11.jpg)

**Comment by sethalt** [comment]
- [ ] Check with Mac Voice Over
- [ ] Check with JAWS

**Comment by sethalt** [comment]
I tested that the above highlighted text is being read with JAWS in IE
