### ISSUE TITLE
Forms containing Month edit field need format instructions 

### ISSUE THREAD

**Issue by JohnHewittCriterion** [flexion/fs-intake-module#823]
Use the same steps as below in the Firefox and Chrome browsers. After typing October in the Month field and pressing the Tab key, JAWS announces 'Invalid Entry'.
Provide instructions stating the required format for the field such as, "Use 2 digit Month Number".
 
 
Steps To Verify With JAWS:
 
Launch the website in IE.
Move to the Apply for a Noncommercial Group Use Permit page at the following URL: https://fs-intake-staging.app.cloud.gov/applications/noncommercial-group-use/new
Locate the "Month" edit field. Note that no instructions are provided notifying user of specific format for the field. Type in October.
Press the Tab key to continue. When reaching the second "Month" edit field JAWS announces 'End date Month Edit Required Oc'.
No instructions were provided notifying user that the "Month" edit field requires the number of the month and not the name.
User was not informed that the "October" entry is invalid.
 
This issue is the same on the Apply for a Temporary Outfitter's Permit page at the following URL: https://fs-intake-staging.app.cloud.gov/applications/temp-outfitters/new
 
When using Firefox or Chrome user is informed of the invalid entry, however, the field must specify format requirements to prevent the errors.
 
Labels or instructions must be provided when content requires user input. 

User typed "17" in the "Year" edit field and an 'invalid entry' alert was immediately reported by JAWS. The "Year" edit field as well as the "Month" edit field have no format instructions.

WCAG: 3.3 Input Assistance - 3.3.2 Labels or Instructions 
EPERM-97

**Comment by npage123** [comment]
- [ ] Check with Mac Voice Over
- [ ] Check with JAWS

**Comment by npage123** [comment]
- [ ] Check with Mac Voice Over
- [ ] Check with JAWS
