### ISSUE TITLE
Application sub-navigation/checklist not accessible via keyboard

### ISSUE THREAD

**Issue by JohnHewittCriterion** [flexion/fs-intake-module#824]
On the “Apply for a temporary outfitters permit” page, there is a sub-navigation menu listing the sections of the application. Each section title is a link to the beginning of the section named in the title. This element also serves as a checklist that indicates whether the required fields of that section have been completed. This list is not included in the tab order and is not accessible using the keyboard. Since each section title is a link, the titles should all be included in the tab order so that they can be accessed when navigating the page using the keyboard.
http://www.w3.org/WAI/WCAG20/quickref/#qr-keyboard-operation-keyboard-operable

![image](https://user-images.githubusercontent.com/28604890/30260310-9b2086d6-9694-11e7-8f0a-ac73f73014fb.png)

WCAG: 2.1 Keyboard Accessible - 2.1.1 Keyboard 
EPERM-126

Tasks
- [ ] Discuss possibility of hiding the side nav from screen readers (John, Seth & Chris)

**Comment by sethalt** [comment]
this gets completed when 825 is completed

**Comment by npage123** [comment]
[ ] - Checked with Mac Voice Over
[ ] - Checked with JAWS

**Comment by npage123** [comment]
- [ ] Check with Mac Voice Over
