### ISSUE TITLE
Side Nav list STEP 1-10 application buttons not keyboard focusable or operable

### ISSUE THREAD

**Issue by JohnHewittCriterion** [flexion/fs-intake-module#825]
Because the step controls are <a> tags with no href they are not keyboard focusable.
Use a native link <a href> element and send keyboard focus to the new spot in the form that moves into view after each step link is activated. 
If you cant use a native link then follow the ARIA link pattern http://w3c.github.io/aria-practices/#link
http://w3c.github.io/aria-practices/examples/link/link.html 
 
WCAG: 2.1 Keyboard Accessible - 2.1.1 Keyboard 
EPERM-128
 
Tasks
- [ ] Discuss possibility of hiding the side nav from screen readers (John, Seth & Chris)

**Comment by npage123** [comment]
- [x] Check with Mac Voice Over
- [ ] Check with JAWS
