### ISSUE TITLE
Temp Outfitter's Permit form has confusing form labels

### ISSUE THREAD

**Issue by JohnHewittCriterion** [flexion/fs-intake-module#828]
User continues to find fields announced by JAWS as 'optional - required'.
Example:
Advertising Advertising description (optional) edit Required
 
Steps To Verify With JAWS:
 
Launch the website.
Activate the "Temp outfitter's permitLogin to apply now with login.gov logo' link.
Press the Tab key to move through the form fields.
When reaching the following two form controls, user is confused whether the fields are optional or required.
JAWS announces:
*'Advertising Advertising description (optional) edit Required'
*'Client's acknowledgement of risk form (optional) Choose file Button Required'
 
Clearly identify form field labels and requirements.

WCAG: 3.3 Input Assistance - 3.3.2 Labels or Instructions 
EPERM-134

**Comment by npage123** [comment]
- [ ] Check with Mac Voice Over
- [ ] Check with JAWS
