### ISSUE TITLE
As an applicant, I would like to receive an email when my application has been accepted.

### ISSUE THREAD

**Issue by colinpmacarthur** [flexion/fs-intake-module#843]
Acceptance Criteria
- [x] Make it clear that the system won't send the user any more automated emails
- [x] Not "out of the woods" has passed a preliminary review, still needs an in-depth review
- [x] Next step is review from admin
- [x] include the custom message from the admin
- [x] Sent when the admin clicks the Accepted button

Definition of Done
- [x] Code unit / e2e tested and comply with QWASP
- [x] No new security vulnerabilities 
- [x] Flexion code review
- [x] Documentation / readme.md updated
- [x] Docker updated
- [x] Compare finished design with mockup
- [ ] Usability tested

Tasks
- [x] Design / UX: Copy (Nate & Peter)
- [x] Design / UX: 18F approves copy (Nate, Colin & Peter)
- [x] Design review of screenshot / content (Nate & Seth)
- [x] Test and compare with mockups (peter)
- [x] Server: Create email template (Seth)
- [x] Server: Move application link to top on admin email for new submission (Seth)
- [x] Server: Trigger email when application status is set to 'accepted' (Eric)
- [x] Server: Fix 401 message from staging (Eric & Laura)

**Comment by npage123** [comment]
Use for reference.

<img width="727" alt="screen shot 2017-09-20 at 9 21 55 am" src="https://user-images.githubusercontent.com/12956624/30664990-2d2dc0ac-9e15-11e7-808e-6b12eba533e3.png">

**Comment by npage123** [comment]
Text for the email:

Subject Line: An update on your recent permit application to the Forest Service.


Permit application status update
*********************************

The permit application listed below has passed a preliminary review! An administrator will now do a more in-depth review and may be contacting you to get any additional details or documents needed. 

Then, if your application is approved, you will receive your permit within 2 weeks of approval.

——Admin custom message inserted here—— 


Application details
*********************************

Event name:
Start date:
End date:
Number of participants:
Number of spectators:
Location:


Contact us
*********************************

If you have questions or need to contact the permit staff at the National Forest Service, please use a method listed below.

Temp outfitter contact
Name: 
Title:
Phone:
Email:


If you would like to submit another permit application visit https://fs-intake-staging.app.cloud.gov/.

Thank you for your interest in our National Forests.

**Comment by colinpmacarthur** [comment]
Looks good to me!
