### ISSUE TITLE
As a special use administrator, I want to un-hold an application. 

### ISSUE THREAD

**Issue by colinpmacarthur** [flexion/fs-intake-module#878]
Acceptance criteria
- [x] Concept of ability to un-hold an application reviewed with special use admins
- [x] A new status is created and applied where needed
- [x] Creation of CTAs on application details page
- [x] Email gets sent to applicant when application is un-held

Definition of Done
- [x] Code unit / e2e tested and comply with QWASP
- [x] No new security vulnerabilities
- [x] Flexion code review
- [x] Documentation / readme.md updated
- [x] Docker updated
- [x] Compare finished design with mockup
- [x] Usability tested

Tasks
- [x] Contact special use admins
- [x] Find out if un-holding is needed
- [x] Figure out what to call new status, create new label (peter, nate)
- [x] Mockup button placement, functionality and text (nate)
- [x] Update frontend to support the new status (seth, chris)
- [x] Email copy (nate)
- [x] Review with collin
- [x] Implement email (seth)
- [x] Trigger email when status changes (seth)

**Comment by dubharmonic** [comment]
Be sure to iterate on the acceptance criteria as we get more info.

**Comment by npage123** [comment]
Proposed email screenshots:
<img width="589" alt="screen shot 2017-10-06 at 10 52 26 am" src="https://user-images.githubusercontent.com/12956624/31286696-9ba262e2-aa84-11e7-9d7d-620fb8a87688.png">
<img width="587" alt="screen shot 2017-10-06 at 10 52 15 am" src="https://user-images.githubusercontent.com/12956624/31286697-9ba615f4-aa84-11e7-9941-8bd5ded259fa.png">

**Comment by npage123** [comment]
Step 1: Admin views list page to chose permit application to change status to "Review".
Step 2: Admin selects the "Remove hold" button.
Step 3: Admin enters message and clicks "Remove hold and notify applicant" button.
Step 4: "Remove hold" button changes back to "Hold" button and admin stays on detail page.

Mockups in clicking order:
![un-hold-application-mockup-rd1-01](https://user-images.githubusercontent.com/12956624/31295582-ad017f30-aaa4-11e7-90a4-528b4d73df48.jpg)
![un-hold-application-mockup-rd1-02](https://user-images.githubusercontent.com/12956624/31295585-ad0c2368-aaa4-11e7-87da-de5bc6f81019.jpg)
![un-hold-application-mockup-rd1-03](https://user-images.githubusercontent.com/12956624/31295583-ad06c378-aaa4-11e7-8a76-382281d82473.jpg)
![un-hold-application-mockup-rd1-04](https://user-images.githubusercontent.com/12956624/31295584-ad0a9f8e-aaa4-11e7-8f08-1e257a803cc4.jpg)
