### ISSUE TITLE
As a special use admin, I would like to be able to better differentiate between "Rejected" and "Cancelled" permit applications.

### ISSUE THREAD

**Issue by npage123** [flexion/fs-intake-module#881]
Acceptance criteria:

When on an application detail page, the reject button reads "Reject, cancel application". And on the list page, we have "Rejected" and "Cancelled" options in the filter dropdown. Proposing to change the reject button to read:

Reject
Notify applicant

Tasks
- [ ] Implement change (Seth, Chris, Nate) 

Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities 
- [ ] Flexion code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by thegoldentoilet** [comment]
Duplicate of 920
