### ISSUE TITLE
As a special use admin, I would like to be more aware that when I accept an application, its information is automatically entered into SUDS.

### ISSUE THREAD

**Issue by npage123** [flexion/fs-intake-module#918]
In usability testing most users had trouble realizing that the e-permit system was going to enter all the application data into SUDS. They also thought it made sense that some call to action to SUDS should be available after accepting applications.

Recommendations:
* Consider changing the CTA “Accept enter into SUDS” to “Accept and send to SUDS”. “Enter” may be taken to mean, “manually enter” where “send” implies “automatically send”.
* Add link to SUDS on Application list page.

Acceptance criteria
- [x] Link to SUDS on the approval screen
- [x] Update wording about accepting an application

Definition of Done
- [x] Code unit / e2e tested and comply with QWASP
 - [x] No new security vulnerabilities
 - [x] Flexion code review
 - [x] Documentation / readme.md updated
 - [x] Docker updated
 - [x] Compare finished design with mockup
 - [x] Usability tested

Tasks
- [x] UX - Decide where CTAs go (Peter & Nate)
- [x] UX/UI - Create mockup (Nate)
- [x] Review mockup with Colin
- [x] Implement

**Comment by npage123** [comment]
Mockup for reference.
<img width="318" alt="screen shot 2017-09-28 at 3 02 14 pm" src="https://user-images.githubusercontent.com/12956624/30987878-17aa34b4-a45e-11e7-8e4f-50b869d23da6.png">

**Comment by npage123** [comment]
Added a text link to SUDS in the header as well as in success messaging whenever an admin accepts an application. Admin list page mockup for reference:
![admin-list-mockup-rd11-01](https://user-images.githubusercontent.com/12956624/30991329-48b3f03e-a46a-11e7-9f4c-b1bbf1474df4.jpg)

**Comment by npage123** [comment]
SUDS CTAs should link to https://iweb.fs.usda.gov/login/common.jsp?option=7

**Comment by colinpmacarthur** [comment]
Basically looks good to me. My only question: Do you think the link will be visible enough? Should it be a button?
