### ISSUE TITLE
As a special use administrator, I would like to cancel an application.

### ISSUE THREAD

**Issue by colinpmacarthur** [flexion/fs-intake-module#920]
Acceptance criteria
- [x] add a cancel button in an "appropriate" place
- [x] copy to define the differences between reject and cancel
- [x] trigger an email to the applicant

Definition of Done
- [x] Code unit / e2e tested and comply with QWASP
- [x] No new security vulnerabilities
- [x] Flexion code review
- [x] Documentation / readme.md updated
- [x] Docker updated
- [x] Compare finished design with mockup
- [x] Usability tested

Tasks
- [x] Add cancel button on application detail page (Nate, Peter & Chris)
- [x] Adjust copy to define the differences between reject and cancel (Nate, Peter & Chris)
- [x] Design / UX: Copy for email (Nate & Peter)
- [x] Design / UX: 18F approves email copy (Colin)
- [x] Implement email (Seth & Chris)
- [x] Design review of screenshot / content (Seth, Chris & Nate)
- [x] Server: Create email template (seth)
- [x] Server: Trigger email to applicant when application status is set to 'cancelled' (seth)

**Comment by lauraGgit** [comment]
This will be before acceptance.

**Comment by npage123** [comment]
Email mockups
<img width="589" alt="screen shot 2017-10-06 at 10 04 23 am" src="https://user-images.githubusercontent.com/12956624/31284317-ce68ea54-aa7d-11e7-8d58-5af79eb823c4.png">

<img width="588" alt="screen shot 2017-10-06 at 10 04 00 am" src="https://user-images.githubusercontent.com/12956624/31284322-d2798a72-aa7d-11e7-8e7f-71aff4da5687.png">
