### ISSUE TITLE
As an applicant, I'd like to be able to edit my application after it's put on hold.

### ISSUE THREAD

**Issue by colinpmacarthur** [flexion/fs-intake-module#965]
Acceptance Criteria (educated guess)
- [ ] both permit types
- [ ] from the view applications screen the applicant can choose to edit the permit application
- [ ] update form should be the same as the new application form
- [ ] changes overwrite previous version

Tasks
- [x] place edit button on application list screen (Nate & Seth)
- [x] extend variables in Angular model for noncommercial (Eric & Seth)
    - [x] if phone numbers exist, pass back everything plus extension, phone digit, phone type (null if they don't exist)
    - [x] if evening phone is empty, don't pass it back (Eric)
    - [x] if org address is empty, don't pass it back (Eric)
    - [x] if secondary address is empty, don't pass it back (Eric)
    - [x] if address fields are empty, pass a null (Eric)
    - [x] datetime range needs to be returned with individual fields (Eric)
    - [x] optional fields needs to be null if blank (Eric)
- [x] add variables to noncommercial update call in API (Eric, Seth)
- [x] extend variables in Angular model for temp outfitter (Eric & Seth)
- [x] add variables to temp outfitter update call in API (Eric, Seth)
- [x] add delete to ApplicationFiles model that also deletes from S3 (Eric)
- [x] add file replace to application edit UI (Eric & Seth)
- [x] Save and cancel buttons (Nate & Eric or Seth)
- [x] Change status to submitted
- [ ] Don't redirect to list screen until files have finished uploading (Seth)
- [ ] Squash bugs
    - [x] Initial "Submitted" status not appearing in application detail after submitting a noncommercial application
    - [x] When adding a secondary permit holder, submitting, then application is put on hold again by admin, applicant goes back in and edit to remove the secondary permit holder, submit and then put back on hold again, go back in to edit, the secondary permit holder is still there
    - [x] After editing and re-submitting application, application status should be "Review"
    - [x] Please remove code below submit button
    - [x] Doesn't appear to be a submitted status for temp outfitter applications. @npage123 try this on a new application. It wont show up on applications older than a week ago.
    - [x] When logged in as an admin, I can edit the applications that are on hold
    - [x] Submitted a temp outfitter application. After putting on hold, when editing application, I entered a valid website url, submitted again and got an error but one that doesn't specify where the error is. @npage123 please test this again. I tried to recreate and couldn't. My thought is that it was an error that had been fixed while you were testing.
    - [x] Need to include the ID number in hold email sent to applicant.
    - [x] Please remove the admin's message in the "Review" email that gets sent to client after they save their application.
    - [x] For noncommercial application, when adding a secondary permit holder in edit mode and save, it doesn't appear in the updated application detail.
    - [x] When in edit mode for both application types, and clicking Cancel button, status' change to "Review".
    - [x] Not necessarily associated with this issue but there's no name reference on temp outfitter application detail.
    - [x] Having the Experience questions checked upon temp outfitter application submission, when editing and unchecking, then saving, they still appear in the updated detail.
    - [x] Having corporation checked upon temp outfitter application submission, when editing and unchecking, then saving, the good-standing file upload still appears in updated detail. 

Definition of Done
- [x] Code unit / e2e tested and comply with QWASP
- [x] No new security vulnerabilities 
- [x] Flexion code review
- [x] Documentation / readme.md / CircleCI updated
- [x] Docker updated
- [x] Compare finished design with mockup
- [ ] Usability tested

**Comment by dubharmonic** [comment]
@sethalt a few questions when you get in:
- phoneType is never saved to the database, and is easy to imply, can we remove that value from the form control?
- where should individual datetime values be set?

**Comment by sethalt** [comment]
Good call on phone type. I'll just remove it.

Datetime values should be in:
``` {   "dateTimeRange": {
    "endDateTime": "",
    "endDay": "",
    "endMonth": "",
    "endYear": "",
    "endHour": "",
    "endMinutes": "",
    "endPeriod": "",
    "startDateTime": "",
    "startDay": "",
    "startMonth": "",
    "startYear": "",
    "startHour": "",
    "startMinutes": "",
    "startPeriod": ""
  }}```
