### ISSUE TITLE
As a Forest Service special uses administrator, I would like to be able to access accepted, closed, and expired applications.

### ISSUE THREAD

**Issue by dubharmonic** [flexion/fs-intake-module#99]
Acceptance Criteria
- [x] A dropdown at the top of the list screen with open/hold, closed/accepted/expired, cancelled, all
- [x] Doesn't include pagination
- [x] Permit application view should not include the status change buttons
- [x] User needs to be able to view attached documents

Definition of Done
- [x] Code unit / e2e tested and comply with QWASP
- [x] No new security vulnerabilities 
- [x] Flexion code review
- [x] Documentation / readme.md updated
- [x] Docker updated
- [x] Compare finished design with mockup
- [x] Usability tested

Tasks
- [x] New API endpoint with other status values (Jesse & Chris)
- [x] add dropdown to the application list screen with a listener to fetch applications (Jesse & Chris)
- [x] design review (Nate & Chris)

**Comment by dubharmonic** [comment]
If an applicant calls in with questions, an admin will need to view the application.

**Comment by dubharmonic** [comment]
For MVP a list view of Accepted, Closed or Expired?

**Comment by npage123** [comment]
Using following screenshot of earlier mockup for reference and fine tuning via pairing.
<img width="516" alt="screen shot 2017-09-20 at 1 15 58 pm" src="https://user-images.githubusercontent.com/12956624/30661882-eb1ec594-9e0a-11e7-9ddf-8130c192952e.png">

**Comment by colinpmacarthur** [comment]
- [ ] In the dropdown selector, we use the word "Rejected," but in other places we use the word "Returned." "Returned is better. Let's standardize on that.
- [ ] When you change your view on permit applications, the success/error messages persist. So, for example, when you reject an application, you go back to the active applications list and then switch to accepted applications, the "You successfully rejected an application" message is still there.
