### ISSUE TITLE
As an applicant, I should not be allowed to enter more characters in the frontend than the API allows in any of the textfields

### ISSUE THREAD

**Issue by lauraGgit** [flexion/fs-intake-module#990]
Acceptance Criteria
- [x] If I enter more characters in an input or textarea, I should receive a frontend validation error.

Tasks
- [x] Language for length validation errors (Nate)
- [x] Make UI validation consistent with API, remember the 400 character limits! (Eric & Seth)

Definition of Done
- [x] Code unit / e2e tested and comply with QWASP
- [x] No new security vulnerabilities 
- [x] Flexion code review
- [x] Documentation / readme.md / CircleCI updated
- [x] Docker updated
- [x] Compare finished design with mockup
- [ ] Usability tested

**Comment by npage123** [comment]
Please add the following below each 400 character limited text area in hint text:
Please limit to 400 characters.

Language for error message:
You have exceeded the 400 character limit in one or more of your descriptions. Please update and submit again.

**Comment by dubharmonic** [comment]
Updated to 512!
