### ISSUE TITLE
As an applicant, If I receive a server error I should be directed to change my application.

### ISSUE THREAD

**Issue by lauraGgit** [flexion/fs-intake-module#991]
## Notes
If you currently submit an application with a value that exceeds the db field length you only receive and error at the alert box to fix your application, and no indication of a validation error. In the console, you will see a vague `500` error with the body of the error as a full sequelize / sql `INSERT` statement in it.

## Acceptance 
- [x] When a db character limit is exceeded suppress the raw sequelize error in the api response body.
- [x] When a db character limit is exceeded, provide an error to the frontend that indicates that length has been exceeded.
- [x] Limit the subfields to 400 characters each, and consistent with 18F/dev #990.
- [x] If the server error, is not about character limits being exceeded, indicate in the error alert that there is a server error (not that the user has errors in their application).

Tasks
- [x] Revisit unexpected error VS bad data scenarios (Eric)
- [x] Migrations on several fields to 400 characters (Eric)
- [x] Draft content for 500 error (Colin, Peter, Nate)
- [x] Handle 4XX vs 500 errors differently, 4XX gives a user friendly message, 500 means `Something went wrong.` (Seth, Eric) 

Definition of Done
- [x] Code unit / e2e tested and comply with QWASP
- [x] No new security vulnerabilities 
- [x] Flexion code review
- [x] Documentation / readme.md / CircleCI updated
- [x] Docker updated
- [x] Compare finished design with mockup
- [ ] Usability tested

**Comment by npage123** [comment]
Proposed content for 500 error:
Something went wrong on our end.
Sorry for the inconvenience but please try again later. 

If you continue to get this error contact fs-permitting-project@gsa.gov.

Screenshot for reference:
<img width="804" alt="screen shot 2017-11-07 at 10 19 52 am" src="https://user-images.githubusercontent.com/12956624/32504454-74e83656-c3a5-11e7-86a3-e1a319f7bf9d.png">

**Comment by colinpmacarthur** [comment]
@dubharmonic A copy small copy edits on this one: 

> Sorry for the inconvenience, but please try again later.

> If you continue to get this error, contact fs-permitting-project@gsa.gov.

**Comment by dubharmonic** [comment]
Updated!
